from app.models import db, Artist


def artists_seed2():
  # artist5
  lizzo = Artist(name="Lizzo",
                     bio="Combining her roots in Houston rap, gospel soul, and classical flute as confidently as she addresses issues of race, sexuality, and body positivity, singer/rapper Lizzo's music abounds with humor and charisma. Her 2013 debut, Lizzobangers, reflected her years in Minneapolis' hip-hop and indie music scenes ('s  was one of its producers), and as time went on, her style became more wide-ranging and melodic. On 2015's self-released Big Grrrl Small World, she added more R&B and gospel to her sound, a trend that continued on her brash major-label debut and breakthrough album, 2019's Cuz I Love You.",
                     image="/static/lizzo.jpeg")
  # artist6
  the_weeknd = Artist(name="The Weeknd",
                    bio="The Weeknd took over pop music & culture on his own terms filtering R&B, Pop,& hip-hop through an ambitious widescreen lens. The multi-platinum 3X GRAMMY Award winner has emerged as one of the most successful & significant artists of the modern era. 2012’s 3X platinum collated 3 breakout mixtapes—House of Balloons, Thursday & Echoes of Silence—into his 1st chart-topping collection followed by his debut LP in 2013. Two years later, “Earned It (Fifty Shades of Grey)” won “Best R&B Performance” & received an Academy Award nod for “Best Original Song” & 4X Platinum  won a GRAMMY for “Best Urban Contemporary Album.” In 2018,  won the same award, making him the 1st artist ever to win twice. His 6-track project My Dear Melancholy marked his 3rd consecutive #1 bow on the Billboard Top 200, & “Pray For Me” with Kendrick Lamar was featured in the trailer for the Academy Award winning Marvel film Black Panther. In 2020 the 80’s-nostalgic track  became a worldwide sensation, igniting viral dance challenges across social media, peaking at #1 in 30+ countries & headlining Mercedes Benz EQC campaign.  held the #1 spot on Billboard 200 for 4 consecutive weeks, marking his 4th #1 album & becoming the first to ever rank #1 on the Billboard 200, Hot 100, and Artist 100 simultaneously.  is the #1 R&B streaming album of all time (followed by  at #2).",
                    image="/static/the-weeknd.jpeg")
  # artist7
  miley_cyrus = Artist(name="Miley Cyrus",
                     bio="Miley Cyrus is one of the most influential artists in pop culture with over 125 million Instagram followers. She has five #1 albums including her 2013 GRAMMY-nominated album Bangerz, also certified 3x platinum in the U.S. In addition, she has had an impressive five sold-out world tours throughout her career. In 2015 she released her free, surprise experimental album, Miley Cyrus and Her Dead Petz, co-produced by Wayne Coyne and other Flaming Lips members. Her sixth album, Younger Now, released in 2017, exceeded 2.2 billion streams. In June of 2019 she starred in an episode of Netflix Black Mirror. The standout role had Cyrus playing popstar Ashley O and featured the track “On A Roll,” which earned 168 million streams, topping the TV Songs chart. Cyrus joins a short list of singers who have charted under three separate names, but is especially rare as she has had two of these chart positions with acting roles.   This summer, Miley released her first single, “Midnight Sky,” from her seventh studio album Plastic Hearts. The song went #1 on iTunes in 68 countries, and the self-directed video has amassed 122 million views leaving fans to witness Miley as the ever-evolving artist that she is. The album features the likes of Billy Idol and Joan Jett. The second single released from the album, “Prisoner,” had massive fan reactions and features Dua Lipa on the track and in the video. Miley also teamed up with Stevie Nicks for the “Edge of Midnight (Midnight Sky Remix).",
                     image="/static/miley-cyrus.jpeg")
  # artist8
  cardi_b = Artist(name="Cardi B",
                         bio="Rapper and entertainer Cardi B made her debut in the late 2010s with a quick ascent to the top of the rap and pop charts. After an initial run of singles that crowned her the first female rapper in nearly two decades to top the Billboard Hot 100 with the hit 'Bodak Yellow,' she issued her Grammy-nominated, critically acclaimed debut album, 2018's Invasion of Privacy, which reached number one and broke additional records with the summer smash 'I Like It.' Capping off her whirlwind breakthrough era, she became the first solo female rapper to win a Grammy for Best Rap Album.",
                         image="/static/cardi-b.jpeg")
  # artist9
  beyonce = Artist(name="Beyoncé",
                   bio="True to form, Beyoncé issued a surprise live album, the Grammy-winning Homecoming, in April 2019. Paired with a concert documentary of the same name, the 40-song chronicle immortalized her 2018 Coachella performance and also included a newly released song, a cover of 's 'Before I Let Go.' Later that year, she not only starred as Nala in the photorealistic remake of The Lion King, but curated the film's accompanying soundtrack, The Lion King: The Gift. Featuring a wealth of African artists collaborating with the likes of , , , , and her co-star Donald Glover, the album also included her single 'Spirit,' which went on to receive both Grammy and Oscar nominations. Black Is King, a companion film to The Lion King: The Gift soundtrack and Beyoncé's second 'visual album,' arrived in July 2020.",
                   image="/static/beyonce.jpeg")
  # artist10
  carly_rae_jepsen = Artist(name="Carly Rae Jepsen",
                            bio='Carly Rae Jepsen’s pristine, prismatic pop has long been the blissful soundtrack for first kisses and swirling romances, but the multi-platinum Grammy, Juno and Polaris Prize nominated Canadian star’s knack for distilling a sea of emotions into brilliant songcraft has wooed critics as deeply as fans. The singer, songwriter, and actress first burst onto the international scene in 2012 with the sly and sublime “Call Me Maybe.” That blockbuster hit from her breakthrough album, Kiss, topped charts in over 47 countries, sold over 20 million singles, and was certified Diamond in the U.S. It also earned her two Grammy nominations for Best Pop Solo Performance and Song of the Year. On her 2015 synth-pop stunner E*MO*TION, Jepsen collaborated with Sia, Blood Orange’s Dev Hynes, and Rostam Batmanglij (Vampire Weekend), expanding her sonic palette with shimmery synths and euphoric dance beats that channel the sugary rush of new flirtations. Noisey declared it the pop album of the year, while the beaming single “I Really Like You” went platinum. Her 2019 follow-up, Dedicated, covered even more musical and emotional ground, as our most hopeful romantic continued to chase her bliss through a breakup. The Atlantic called the album “brilliant” with its “godlike bops.” Jepsen returned again in May 2020 with a gift for her fans: Dedicated Side B, a buoyant set of dance-floor candy that affirmed her status as pop’s undefeatable ambassador of love.',
                            image="/static/carly-rae-jepsen.jpeg")
  # artist11
  billie_eilish = Artist(name="Billie Eilish",
                         bio="18-year-old global pop-phenom Billie Eilish has fast become one of the biggest stars to emerge since the release of her debut single “ocean eyes,” and continues to shatter the ceiling of music with her genre-defying sound. Fast forward from her humble breakout, Billie’s album WHEN WE ALL FALL ASLEEP, WHERE DO WE GO? debuted at #1 in the Billboard 200 in the U.S, as well as in the UK, Australia, Canada, New Zealand, Netherlands, Belgium, Ireland, Sweden, Norway, Finland and many more. It is now the biggest North American debut of the decade (male, female or group), shifting 313,000 units in the first week and has already hit NUMBER 1 in the Billboard 200 album 3 times since its release in March, earning Billie more than 15 billion combined streams worldwide to date - and has won her 5 GRAMMYs (Best New Artist, Album Of The Year, Record Of The Year, Song Of The Year, Best Pop Vocal Album). Billie is currently on her sold-out WHEN WE ALL FALL ASLEEP, WORLD TOUR and about to embark on her Arena WHERE DO WE GO? WORLD TOUR.",
                         image="/static/billie-eilish.jpeg")
  # artist12
  doja_cat = Artist(name="Doja Cat",
                    bio="Born and raised in L.A., Doja Cat made her first upload to Soundcloud in 2013 at just 16-years-old. She developed a knack for music by studying piano and dance as a kid and listening to the likes of Busta Rhymes, Erykah Badu, Nicki Minaj, Drake, and more. Soon, she went from obsessing over Catwoman (the Halle Berry version) to “crate digging” on YouTube. Signed to Kemosabe/RCA during 2014, she unveiled her acclaimed Purrr! EP. Its lead single “So High” impressively racked up over 30 million cumulative streams and garnered praise from tastemakers such as Fader, Vibe, Paper, Pigeons & Planes, and more. Cooking up vibrantly, candy-coated beats, dropping bars doubled-up on double entendre, and singing with claws out, Amala unlocks a sweetly sexy world soundtracked by wild hip-hop, twisted pop, and smoked-out R&B. Asserting a feline-esque dominance and a style that can only be described as every color in a box of crayons, Doja Cat’s unapologetic charisma, charm, and confidence immediately take center stage. In August 2018, she released what would become her viral hit “Mooo!” which enjoyed over 10 million views on YouTube and Twitter in just a couple of days and was met with critical acclaim. In March 2019, she released the Amala Deluxe album which included her brand new song “Juicy.” With the release of Hot Pink, Doja’s ability to create hit records that are uniquely her own are what will continue to make her a standout act in 2019.",
                    image="/static/doja-cat.jpeg")
  # artist13
  nicki_minaj = Artist(name="Nicki Minaj",
                       bio="Nicki Minaj skyrocketed to superstardom with a talent that brought to mind past legends but wasn't quite like anything that came before her. Her early days included shaky attempts at an acting career and losing her job at Red Lobster for being rude to customers, Minaj progressed quickly from MySpace demos to nationally adored mixtapes to household-name status. She worked closely with , , , and virtually every upper-echelon rapper and pop star before ascending to the level of fame that had her selling millions of albums and performing in the Super Bowl halftime show. As a rapper, Minaj is ferocious, known for a unique flow that turns on a dime from sugary to snarling, with razor-sharp wordplay and mercilessly blunt lyricism. Her range isn't limited to mixtape fire, however, as her crossovers into pop territory have yielded some of her most successful work. Her 2010 debut album Pink Friday saw the rapper branching out into radio-friendly melodicism, and accordingly it was the first of her albums to sell in the multi-platinum reaches and top chart positions internationally. Establishing herself as more an iconic presence than an album artist, Minaj released well over 70 singles under her own name in her first decade of recording, and stole the show in guest appearances on countless hits for other artists. As one of the most successful rappers and crossover pop stars of her age, Minaj is part of a lineage that includesand Missy Elliot, Beyonce, and Drake.",
                       image="/static/nicki-minaj.jpeg")
  # artist14
  kacey_musgraves = Artist(name="Kacey Musgraves",
                           bio="Kacey Musgraves’ most recent release, a duet “Easy” with Troye Sivan, was released in December 2020 and hints at the continuing evolution of this multi-genre artist. The 6x GRAMMY Award-winning singer-songwriter’s studio album Golden Hour (2018, MCA Nashville) earned Musgraves her third No. 1 debut on Billboard’s Top Country Albums chart and distinguished her as the third artist ever to take home Album of the Year at the GRAMMY Awards, Country Music Association Awards, and Academy of Country Music Awards. Golden Hour was named one of the best albums of 2018 by everyone from Apple Music, NPR, Time, The Associated Press, Rolling Stone, Pitchfork, Billboard, GQ, Esquire, American Songwriter, Complex, Consequence of Sound, and Vulture, among others. In support of the album, Musgraves played the biggest venues of her career, including New York City’s Radio City Music Hall and her first headlining arena show at Nashville’s Bridgestone Arena, and to top it off she became the first-ever female country artist to play Coachella. Musgraves has been honored at Billboard’s Women in Music event, Variety’s Power of Women event, and celebrated the opening of her exhibit, All of the Colors, at the Country Music Hall of Fame and Museum. At the 2019 CMAs, Musgraves received two wins for Female Vocalist of the Year and for Music Video of the Year for “Rainbow.”",
                           image="/static/kacey-musgraves.jpeg")
  # artist15
  kim_petras = Artist(name="Kim Petras",
                      bio="Fast-rising pop sensation Kim Petras has become one of music’s most buzzed-about artists with the release of her latest single “Malibu” and her critically acclaimed debut full-length Clarity. Kim will be making her Coachella debut in October after recently wrapping her international The Clarity Tour and selling out her first ever headline tour last summer in minutes during presale. Kim’s undeniable voice and imaginative artistry have skyrocketed her to international recognition as one of pop’s most promising talents while earning major mainstream media acclaim from the likes of NY Times, NPR, Vanity Fair, People, Rolling Stone, MTV, Glamour, Elle, Variety, Allure, Billboard, Cosmopolitan, Paper, V Magazine, Noisey, OUT, Pitchfork, i-D, Refinery29, and more.   First breaking out with her #1 Spotify Global Viral 50 bop “I Don’t Want It At All,” Kim launched into Top 40 radio with her pop hit “Heart to Break,” opened for Troye Sivan’s nationwide Bloom Tour last year, revived and redefined Halloween music with her spooky project TURN OFF THE LIGHT, collaborated with Charli XCX, Cheat Codes, MAX, SOPHIE, Lil Aaron, and more, appeared on “How It’s Done” from the Ariana-Grande-produced Charlie’s Angels soundtrack, and has been featured on multiple billboards in New York, London, and Los Angeles as a Spotify RISE artist.",
                      image="/static/kim-petras.jpeg")
  # artist16
  blackpink = Artist(name="BLACKPINK",
                     bio="BLACKPINK, YG Entertainment’s 4-member Korean female group consisting of JISOO, JENNIE, ROSÉ, and LISA, released their debut album [SQUARE ONE] in August 2016. Soon after [SQUARE TWO] and [AS IF IT’S YOUR LAST] were released and dominated the music charts which drew great attention.In June 2018, they released their 1st Mini Album [SQUARE UP] and their title song ‘뚜두뚜두 (DDU-DU DDU- DU)’ M/V broke many records and was acknowledged as the first K-Pop group to earn 1 Billion views on YouTube. In April 2019, with their successful release of their 2nd Mini Album [KILL THIS LOVE], they’ve become the first K-Pop girl group to perform at the Coachella Music Festival, while wrapping up their 2019 World Tour [IN YOUR AREA] held across 23 cities of 4 continents. Ahead of their first studio album [THE ALBUM], BLACKPINK dropped two pre-release singles; the record- smashing hit [How You Like That] in June and [Ice Cream (with Selena Gomez)] in August, which debuted at No.13 on the Billboard Hot 100 chart. Along with this immense worldwide recognition, [THE ALBUM] released this October surpassed 1 million pre-orders, the first K-Pop girl group to reach this milestone. With their global partnership with Universal Music Group (UMG) and Interscope Records, BLACKPINK will continue to share their music worldwide.",
                     image="/static/blackpink.jpeg")
  # artist17
  elton_john = Artist(name="Elton John",
                      bio="Elton John is one of the top-selling solo artists of all time, with 1 diamond, 40 platinum or multi-platinum, and 23 gold albums, and over 50 Top 40 hits. He has sold more than 300 million records worldwide. He holds the record for the biggest-selling single of all time, “Candle in the Wind 1997”, which sold over 33 million copies. ‘Diamonds’, the Ultimate Greatest Hits album, became Elton’s 40th UK Top 40 album and celebrated 50 years of his songwriting partnership with Bernie Taupin. August 2018 saw Elton named as the most successful male solo artist in Billboard Hot 100 chart history, having logged 67 entries, including nine No. 1s and 27 Top 10s. Elton's ‘Farewell Yellow Brick Road’ tour started in September 2018 and will encompass 5 continents, and over 350 dates. This 3-year-long tour marks his retirement from touring after more than 50 years on the road and was named Billboard's Top Rock Tour of 2019. To date, Elton has delivered more than 4,000 performances in more than 80 countries. 2019 saw the release of 'Rocketman', an Oscar and Golden Globe winning epic fantasy musical motion picture of his life, and his critically acclaimed autobiography ‘Me’, a global bestseller. The Elton John AIDS Foundation is one of the leading non-profit HIV/AIDS organisations and has raised over $450 million in the global fight against HIV/AIDS.",
                      image="/static/elton-john.jpeg")

  db.session.add(lizzo)
  db.session.add(the_weeknd)
  db.session.add(miley_cyrus)
  db.session.add(cardi_b)
  db.session.add(beyonce)
  db.session.add(carly_rae_jepsen)
  db.session.add(billie_eilish)
  db.session.add(doja_cat)
  db.session.add(nicki_minaj)
  db.session.add(kacey_musgraves)
  db.session.add(kim_petras)
  db.session.add(blackpink)
  db.session.add(elton_john)
  db.session.commit()

def undo_artists_seed2():
  db.session.execute('TRUNCATE artists CASCADE;')
  db.session.commit()
