"""added playlist_tracks model

Revision ID: bb6bb64a85e5
Revises: fd8cc4f0b578
Create Date: 2021-03-31 11:12:30.577317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb6bb64a85e5'
down_revision = 'fd8cc4f0b578'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playlist_tracks')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playlist_tracks',
    sa.Column('track_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('playlist_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], name='playlist_tracks_playlist_id_fkey'),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], name='playlist_tracks_track_id_fkey'),
    sa.PrimaryKeyConstraint('track_id', 'playlist_id', name='playlist_tracks_pkey')
    )
    # ### end Alembic commands ###
